#############################################################################
# Makefile for building: cmbbqt
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  cmbbqt.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cmbbqt.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1y -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cmbbqt1.0.0
DISTDIR = /home/adminval11/cmbbqt/.tmp/cmbbqt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5SerialPort.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		calibrationmbac.cpp \
		config.cpp \
		xmldocument.cpp \
		ccmbb.cpp \
		datamodules.cpp \
		cmbblistmodules.cpp \
		viewmodules.cpp \
		viewbase.cpp \
		sport.cpp \
		protocol.cpp \
		tinyxml/tinystr.cpp \
		tinyxml/tinyxml.cpp \
		tinyxml/tinyxmlerror.cpp \
		tinyxml/tinyxmlparser.cpp \
		modules.cpp \
		myprogressbar.cpp \
		logfile.cpp \
		calibratedialog.cpp \
		settingsanalog.cpp \
		rateconstants.cpp \
		settingmodule.cpp \
		Style.cpp \
		testmodule.cpp \
		test.cpp \
		worker.cpp \
		testtimer.cpp \
		testuart1.cpp \
		testled.cpp \
		testuart0.cpp \
		checkknoawo.cpp \
		testdiscrnbc.cpp \
		testcheckfain1.cpp \
		testacp.cpp \
		testcalibrch.cpp \
		testdiscrnnc.cpp \
		about.cpp \
		testrds.cpp \
		discretrds.cpp \
		discritem.cpp \
		comdtords.cpp \
		daccalibration.cpp \
		mydataport.cpp \
		calibrationcheck.cpp qrc_images.cpp \
		moc_calibrationmbac.cpp \
		moc_config.cpp \
		moc_xmldocument.cpp \
		moc_ccmbb.cpp \
		moc_cmbblistmodules.cpp \
		moc_sport.cpp \
		moc_myprogressbar.cpp \
		moc_calibratedialog.cpp \
		moc_settingsanalog.cpp \
		moc_rateconstants.cpp \
		moc_settingmodule.cpp \
		moc_Style.cpp \
		moc_testmodule.cpp \
		moc_worker.cpp \
		moc_testtimer.cpp \
		moc_testuart1.cpp \
		moc_testled.cpp \
		moc_testuart0.cpp \
		moc_checkknoawo.cpp \
		moc_testdiscrnbc.cpp \
		moc_testcheckfain1.cpp \
		moc_testacp.cpp \
		moc_testcalibrch.cpp \
		moc_testdiscrnnc.cpp \
		moc_testrds.cpp \
		moc_discretrds.cpp \
		moc_discritem.cpp \
		moc_comdtords.cpp \
		moc_daccalibration.cpp \
		moc_mydataport.cpp \
		moc_calibrationcheck.cpp
OBJECTS       = main.o \
		calibrationmbac.o \
		config.o \
		xmldocument.o \
		ccmbb.o \
		datamodules.o \
		cmbblistmodules.o \
		viewmodules.o \
		viewbase.o \
		sport.o \
		protocol.o \
		tinystr.o \
		tinyxml.o \
		tinyxmlerror.o \
		tinyxmlparser.o \
		modules.o \
		myprogressbar.o \
		logfile.o \
		calibratedialog.o \
		settingsanalog.o \
		rateconstants.o \
		settingmodule.o \
		Style.o \
		testmodule.o \
		test.o \
		worker.o \
		testtimer.o \
		testuart1.o \
		testled.o \
		testuart0.o \
		checkknoawo.o \
		testdiscrnbc.o \
		testcheckfain1.o \
		testacp.o \
		testcalibrch.o \
		testdiscrnnc.o \
		about.o \
		testrds.o \
		discretrds.o \
		discritem.o \
		comdtords.o \
		daccalibration.o \
		mydataport.o \
		calibrationcheck.o \
		qrc_images.o \
		moc_calibrationmbac.o \
		moc_config.o \
		moc_xmldocument.o \
		moc_ccmbb.o \
		moc_cmbblistmodules.o \
		moc_sport.o \
		moc_myprogressbar.o \
		moc_calibratedialog.o \
		moc_settingsanalog.o \
		moc_rateconstants.o \
		moc_settingmodule.o \
		moc_Style.o \
		moc_testmodule.o \
		moc_worker.o \
		moc_testtimer.o \
		moc_testuart1.o \
		moc_testled.o \
		moc_testuart0.o \
		moc_checkknoawo.o \
		moc_testdiscrnbc.o \
		moc_testcheckfain1.o \
		moc_testacp.o \
		moc_testcalibrch.o \
		moc_testdiscrnnc.o \
		moc_testrds.o \
		moc_discretrds.o \
		moc_discritem.o \
		moc_comdtords.o \
		moc_daccalibration.o \
		moc_mydataport.o \
		moc_calibrationcheck.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cmbbqt.pro calibrationmbac.h \
		config.h \
		xmldocument.h \
		ccmbb.h \
		datamodules.h \
		cmbblistmodules.h \
		viewmodules.h \
		viewbase.h \
		sport.h \
		protocol.h \
		tinyxml/tinystr.h \
		tinyxml/tinyxml.h \
		modules.h \
		myprogressbar.h \
		logfile.h \
		calibratedialog.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		Style.h \
		testmodule.h \
		test.h \
		worker.h \
		testtimer.h \
		testuart1.h \
		testled.h \
		testuart0.h \
		checkknoawo.h \
		testdiscrnbc.h \
		testcheckfain1.h \
		testacp.h \
		testcalibrch.h \
		testdiscrnnc.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		comdtords.h \
		daccalibration.h \
		mydataport.h \
		consts.h \
		calibrationcheck.h main.cpp \
		calibrationmbac.cpp \
		config.cpp \
		xmldocument.cpp \
		ccmbb.cpp \
		datamodules.cpp \
		cmbblistmodules.cpp \
		viewmodules.cpp \
		viewbase.cpp \
		sport.cpp \
		protocol.cpp \
		tinyxml/tinystr.cpp \
		tinyxml/tinyxml.cpp \
		tinyxml/tinyxmlerror.cpp \
		tinyxml/tinyxmlparser.cpp \
		modules.cpp \
		myprogressbar.cpp \
		logfile.cpp \
		calibratedialog.cpp \
		settingsanalog.cpp \
		rateconstants.cpp \
		settingmodule.cpp \
		Style.cpp \
		testmodule.cpp \
		test.cpp \
		worker.cpp \
		testtimer.cpp \
		testuart1.cpp \
		testled.cpp \
		testuart0.cpp \
		checkknoawo.cpp \
		testdiscrnbc.cpp \
		testcheckfain1.cpp \
		testacp.cpp \
		testcalibrch.cpp \
		testdiscrnnc.cpp \
		about.cpp \
		testrds.cpp \
		discretrds.cpp \
		discritem.cpp \
		comdtords.cpp \
		daccalibration.cpp \
		mydataport.cpp \
		calibrationcheck.cpp
QMAKE_TARGET  = cmbbqt
DESTDIR       = 
TARGET        = cmbbqt


first: all
####### Build rules

cmbbqt:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cmbbqt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cmbbqt.pro \
		images.qrc
	$(QMAKE) -o Makefile cmbbqt.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cmbbqt.pro:
images.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile cmbbqt.pro -spec linux-g++

qmake_all: FORCE


all: Makefile cmbbqt

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents calibrationmbac.h config.h xmldocument.h ccmbb.h datamodules.h cmbblistmodules.h viewmodules.h viewbase.h sport.h protocol.h tinyxml/tinystr.h tinyxml/tinyxml.h modules.h myprogressbar.h logfile.h calibratedialog.h settingsanalog.h rateconstants.h settingmodule.h Style.h testmodule.h test.h worker.h testtimer.h testuart1.h testled.h testuart0.h checkknoawo.h testdiscrnbc.h testcheckfain1.h testacp.h testcalibrch.h testdiscrnnc.h about.h testrds.h discretrds.h discritem.h comdtords.h daccalibration.h mydataport.h consts.h calibrationcheck.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp calibrationmbac.cpp config.cpp xmldocument.cpp ccmbb.cpp datamodules.cpp cmbblistmodules.cpp viewmodules.cpp viewbase.cpp sport.cpp protocol.cpp tinyxml/tinystr.cpp tinyxml/tinyxml.cpp tinyxml/tinyxmlerror.cpp tinyxml/tinyxmlparser.cpp modules.cpp myprogressbar.cpp logfile.cpp calibratedialog.cpp settingsanalog.cpp rateconstants.cpp settingmodule.cpp Style.cpp testmodule.cpp test.cpp worker.cpp testtimer.cpp testuart1.cpp testled.cpp testuart0.cpp checkknoawo.cpp testdiscrnbc.cpp testcheckfain1.cpp testacp.cpp testcalibrch.cpp testdiscrnnc.cpp about.cpp testrds.cpp discretrds.cpp discritem.cpp comdtords.cpp daccalibration.cpp mydataport.cpp calibrationcheck.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		/usr/lib/qt5/bin/rcc \
		../cmbbImages/setting_tools.png \
		../cmbbImages/measure.png \
		../cmbbImages/hand_fuck.png \
		../cmbbImages/find.png \
		../cmbbImages/aa.png \
		../cmbbImages/accept.png \
		../cmbbImages/calibr.png \
		../cmbbImages/lightbulb.png \
		../cmbbImages/network_adapter.png \
		../cmbbImages/convert_color_to_gray.png \
		../cmbbImages/system_monitor.png \
		../cmbbImages/door_in.png \
		../cmbbImages/find1.png \
		../cmbbImages/i1.png \
		../cmbbImages/i2.png \
		../cmbbImages/i3.png \
		../cmbbImages/application_edit.png \
		../cmbbImages/construction.png \
		../cmbbImages/hand_point.png \
		../cmbbImages/ask_and_answer.png \
		../cmbbImages/ind1.png \
		../cmbbImages/settings2.png \
		../cmbbImages/ustav.png \
		../cmbbImages/database_gear.png
	/usr/lib/qt5/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1y -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_calibrationmbac.cpp moc_config.cpp moc_xmldocument.cpp moc_ccmbb.cpp moc_cmbblistmodules.cpp moc_sport.cpp moc_myprogressbar.cpp moc_calibratedialog.cpp moc_settingsanalog.cpp moc_rateconstants.cpp moc_settingmodule.cpp moc_Style.cpp moc_testmodule.cpp moc_worker.cpp moc_testtimer.cpp moc_testuart1.cpp moc_testled.cpp moc_testuart0.cpp moc_checkknoawo.cpp moc_testdiscrnbc.cpp moc_testcheckfain1.cpp moc_testacp.cpp moc_testcalibrch.cpp moc_testdiscrnnc.cpp moc_testrds.cpp moc_discretrds.cpp moc_discritem.cpp moc_comdtords.cpp moc_daccalibration.cpp moc_mydataport.cpp moc_calibrationcheck.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_calibrationmbac.cpp moc_config.cpp moc_xmldocument.cpp moc_ccmbb.cpp moc_cmbblistmodules.cpp moc_sport.cpp moc_myprogressbar.cpp moc_calibratedialog.cpp moc_settingsanalog.cpp moc_rateconstants.cpp moc_settingmodule.cpp moc_Style.cpp moc_testmodule.cpp moc_worker.cpp moc_testtimer.cpp moc_testuart1.cpp moc_testled.cpp moc_testuart0.cpp moc_checkknoawo.cpp moc_testdiscrnbc.cpp moc_testcheckfain1.cpp moc_testacp.cpp moc_testcalibrch.cpp moc_testdiscrnnc.cpp moc_testrds.cpp moc_discretrds.cpp moc_discritem.cpp moc_comdtords.cpp moc_daccalibration.cpp moc_mydataport.cpp moc_calibrationcheck.cpp
moc_calibrationmbac.cpp: calibrationmbac.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		myprogressbar.h \
		consts.h \
		calibrationcheck.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include calibrationmbac.h -o moc_calibrationmbac.cpp

moc_config.cpp: config.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		xmldocument.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include config.h -o moc_config.cpp

moc_xmldocument.cpp: xmldocument.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include xmldocument.h -o moc_xmldocument.cpp

moc_ccmbb.cpp: ccmbb.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ccmbb.h -o moc_ccmbb.cpp

moc_cmbblistmodules.cpp: cmbblistmodules.h \
		datamodules.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cmbblistmodules.h -o moc_cmbblistmodules.cpp

moc_sport.cpp: sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include sport.h -o moc_sport.cpp

moc_myprogressbar.cpp: myprogressbar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include myprogressbar.h -o moc_myprogressbar.cpp

moc_calibratedialog.cpp: calibratedialog.h \
		myprogressbar.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include calibratedialog.h -o moc_calibratedialog.cpp

moc_settingsanalog.cpp: settingsanalog.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		modules.h \
		myprogressbar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include settingsanalog.h -o moc_settingsanalog.cpp

moc_rateconstants.cpp: rateconstants.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		myprogressbar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include rateconstants.h -o moc_rateconstants.cpp

moc_settingmodule.cpp: settingmodule.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include settingmodule.h -o moc_settingmodule.cpp

moc_Style.cpp: Style.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Style.h -o moc_Style.cpp

moc_testmodule.cpp: testmodule.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		worker.h \
		testtimer.h \
		testuart1.h \
		testuart0.h \
		testled.h \
		checkknoawo.h \
		testdiscrnbc.h \
		testcheckfain1.h \
		testacp.h \
		testcalibrch.h \
		testdiscrnnc.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testmodule.h -o moc_testmodule.cpp

moc_worker.cpp: worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include worker.h -o moc_worker.cpp

moc_testtimer.cpp: testtimer.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testtimer.h -o moc_testtimer.cpp

moc_testuart1.cpp: testuart1.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testuart1.h -o moc_testuart1.cpp

moc_testled.cpp: testled.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testled.h -o moc_testled.cpp

moc_testuart0.cpp: testuart0.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testuart0.h -o moc_testuart0.cpp

moc_checkknoawo.cpp: checkknoawo.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include checkknoawo.h -o moc_checkknoawo.cpp

moc_testdiscrnbc.cpp: testdiscrnbc.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testdiscrnbc.h -o moc_testdiscrnbc.cpp

moc_testcheckfain1.cpp: testcheckfain1.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testcheckfain1.h -o moc_testcheckfain1.cpp

moc_testacp.cpp: testacp.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testacp.h -o moc_testacp.cpp

moc_testcalibrch.cpp: testcalibrch.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testcalibrch.h -o moc_testcalibrch.cpp

moc_testdiscrnnc.cpp: testdiscrnnc.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testdiscrnnc.h -o moc_testdiscrnnc.cpp

moc_testrds.cpp: testrds.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		comdtords.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include testrds.h -o moc_testrds.cpp

moc_discretrds.cpp: discretrds.h \
		datamodules.h \
		discritem.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include discretrds.h -o moc_discretrds.cpp

moc_discritem.cpp: discritem.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include discritem.h -o moc_discritem.cpp

moc_comdtords.cpp: comdtords.h \
		datamodules.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include comdtords.h -o moc_comdtords.cpp

moc_daccalibration.cpp: daccalibration.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include daccalibration.h -o moc_daccalibration.cpp

moc_mydataport.cpp: mydataport.h \
		logfile.h \
		protocol.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mydataport.h -o moc_mydataport.cpp

moc_calibrationcheck.cpp: calibrationcheck.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/adminval11/cmbbqt/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/adminval11/cmbbqt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include calibrationcheck.h -o moc_calibrationcheck.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp config.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		xmldocument.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

calibrationmbac.o: calibrationmbac.cpp calibrationmbac.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		myprogressbar.h \
		consts.h \
		calibrationcheck.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		calibratedialog.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrationmbac.o calibrationmbac.cpp

config.o: config.cpp sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		config.h \
		xmldocument.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

xmldocument.o: xmldocument.cpp xmldocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmldocument.o xmldocument.cpp

ccmbb.o: ccmbb.cpp ccmbb.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h \
		Style.h \
		testmodule.h \
		testtimer.h \
		testuart1.h \
		testuart0.h \
		testled.h \
		checkknoawo.h \
		testdiscrnbc.h \
		testcheckfain1.h \
		testacp.h \
		testcalibrch.h \
		testdiscrnnc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccmbb.o ccmbb.cpp

datamodules.o: datamodules.cpp datamodules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datamodules.o datamodules.cpp

cmbblistmodules.o: cmbblistmodules.cpp cmbblistmodules.h \
		datamodules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmbblistmodules.o cmbblistmodules.cpp

viewmodules.o: viewmodules.cpp viewmodules.h \
		viewbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewmodules.o viewmodules.cpp

viewbase.o: viewbase.cpp viewbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewbase.o viewbase.cpp

sport.o: sport.cpp sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		xmldocument.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sport.o sport.cpp

protocol.o: protocol.cpp protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protocol.o protocol.cpp

tinystr.o: tinyxml/tinystr.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinystr.o tinyxml/tinystr.cpp

tinyxml.o: tinyxml/tinyxml.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml.o tinyxml/tinyxml.cpp

tinyxmlerror.o: tinyxml/tinyxmlerror.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlerror.o tinyxml/tinyxmlerror.cpp

tinyxmlparser.o: tinyxml/tinyxmlparser.cpp tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlparser.o tinyxml/tinyxmlparser.cpp

modules.o: modules.cpp modules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modules.o modules.cpp

myprogressbar.o: myprogressbar.cpp myprogressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myprogressbar.o myprogressbar.cpp

logfile.o: logfile.cpp logfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logfile.o logfile.cpp

calibratedialog.o: calibratedialog.cpp ccmbb.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibratedialog.o calibratedialog.cpp

settingsanalog.o: settingsanalog.cpp datamodules.h \
		settingsanalog.h \
		sport.h \
		logfile.h \
		protocol.h \
		modules.h \
		myprogressbar.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingsanalog.o settingsanalog.cpp

rateconstants.o: rateconstants.cpp rateconstants.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		myprogressbar.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rateconstants.o rateconstants.cpp

settingmodule.o: settingmodule.cpp settingmodule.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settingmodule.o settingmodule.cpp

Style.o: Style.cpp Style.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Style.o Style.cpp

testmodule.o: testmodule.cpp ccmbb.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h \
		testmodule.h \
		testtimer.h \
		testuart1.h \
		testuart0.h \
		testled.h \
		checkknoawo.h \
		testdiscrnbc.h \
		testcheckfain1.h \
		testacp.h \
		testcalibrch.h \
		testdiscrnnc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testmodule.o testmodule.cpp

test.o: test.cpp test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		ccmbb.h \
		sport.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.cpp

worker.o: worker.cpp worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		xmldocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o worker.o worker.cpp

testtimer.o: testtimer.cpp testtimer.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testtimer.o testtimer.cpp

testuart1.o: testuart1.cpp testuart1.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testuart1.o testuart1.cpp

testled.o: testled.cpp testled.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testled.o testled.cpp

testuart0.o: testuart0.cpp testuart0.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testuart0.o testuart0.cpp

checkknoawo.o: checkknoawo.cpp checkknoawo.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkknoawo.o checkknoawo.cpp

testdiscrnbc.o: testdiscrnbc.cpp testdiscrnbc.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testdiscrnbc.o testdiscrnbc.cpp

testcheckfain1.o: testcheckfain1.cpp testcheckfain1.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testcheckfain1.o testcheckfain1.cpp

testacp.o: testacp.cpp testacp.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testacp.o testacp.cpp

testcalibrch.o: testcalibrch.cpp testcalibrch.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testcalibrch.o testcalibrch.cpp

testdiscrnnc.o: testdiscrnnc.cpp testdiscrnnc.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		worker.h \
		logfile.h \
		protocol.h \
		datamodules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testdiscrnnc.o testdiscrnnc.cpp

about.o: about.cpp about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o about.cpp

testrds.o: testrds.cpp testrds.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		comdtords.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		calibrationcheck.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o testrds.o testrds.cpp

discretrds.o: discretrds.cpp discretrds.h \
		datamodules.h \
		discritem.h \
		testrds.h \
		sport.h \
		logfile.h \
		protocol.h \
		worker.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o discretrds.o discretrds.cpp

discritem.o: discritem.cpp discritem.h \
		discretrds.h \
		datamodules.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o discritem.o discritem.cpp

comdtords.o: comdtords.cpp comdtords.h \
		datamodules.h \
		xmldocument.h \
		protocol.h \
		discretrds.h \
		discritem.h \
		testrds.h \
		sport.h \
		logfile.h \
		worker.h \
		test.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comdtords.o comdtords.cpp

daccalibration.o: daccalibration.cpp daccalibration.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o daccalibration.o daccalibration.cpp

mydataport.o: mydataport.cpp mydataport.h \
		logfile.h \
		protocol.h \
		xmldocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mydataport.o mydataport.cpp

calibrationcheck.o: calibrationcheck.cpp calibrationcheck.h \
		datamodules.h \
		sport.h \
		logfile.h \
		protocol.h \
		ccmbb.h \
		viewmodules.h \
		viewbase.h \
		cmbblistmodules.h \
		modules.h \
		tinyxml/tinyxml.h \
		tinyxml/tinystr.h \
		myprogressbar.h \
		calibratedialog.h \
		calibrationmbac.h \
		consts.h \
		settingsanalog.h \
		rateconstants.h \
		settingmodule.h \
		about.h \
		testrds.h \
		discretrds.h \
		discritem.h \
		worker.h \
		test.h \
		comdtords.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calibrationcheck.o calibrationcheck.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_calibrationmbac.o: moc_calibrationmbac.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrationmbac.o moc_calibrationmbac.cpp

moc_config.o: moc_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_config.o moc_config.cpp

moc_xmldocument.o: moc_xmldocument.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xmldocument.o moc_xmldocument.cpp

moc_ccmbb.o: moc_ccmbb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ccmbb.o moc_ccmbb.cpp

moc_cmbblistmodules.o: moc_cmbblistmodules.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmbblistmodules.o moc_cmbblistmodules.cpp

moc_sport.o: moc_sport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sport.o moc_sport.cpp

moc_myprogressbar.o: moc_myprogressbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myprogressbar.o moc_myprogressbar.cpp

moc_calibratedialog.o: moc_calibratedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibratedialog.o moc_calibratedialog.cpp

moc_settingsanalog.o: moc_settingsanalog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingsanalog.o moc_settingsanalog.cpp

moc_rateconstants.o: moc_rateconstants.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rateconstants.o moc_rateconstants.cpp

moc_settingmodule.o: moc_settingmodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settingmodule.o moc_settingmodule.cpp

moc_Style.o: moc_Style.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Style.o moc_Style.cpp

moc_testmodule.o: moc_testmodule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testmodule.o moc_testmodule.cpp

moc_worker.o: moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_worker.o moc_worker.cpp

moc_testtimer.o: moc_testtimer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testtimer.o moc_testtimer.cpp

moc_testuart1.o: moc_testuart1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testuart1.o moc_testuart1.cpp

moc_testled.o: moc_testled.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testled.o moc_testled.cpp

moc_testuart0.o: moc_testuart0.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testuart0.o moc_testuart0.cpp

moc_checkknoawo.o: moc_checkknoawo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkknoawo.o moc_checkknoawo.cpp

moc_testdiscrnbc.o: moc_testdiscrnbc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testdiscrnbc.o moc_testdiscrnbc.cpp

moc_testcheckfain1.o: moc_testcheckfain1.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testcheckfain1.o moc_testcheckfain1.cpp

moc_testacp.o: moc_testacp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testacp.o moc_testacp.cpp

moc_testcalibrch.o: moc_testcalibrch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testcalibrch.o moc_testcalibrch.cpp

moc_testdiscrnnc.o: moc_testdiscrnnc.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testdiscrnnc.o moc_testdiscrnnc.cpp

moc_testrds.o: moc_testrds.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_testrds.o moc_testrds.cpp

moc_discretrds.o: moc_discretrds.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_discretrds.o moc_discretrds.cpp

moc_discritem.o: moc_discritem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_discritem.o moc_discritem.cpp

moc_comdtords.o: moc_comdtords.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comdtords.o moc_comdtords.cpp

moc_daccalibration.o: moc_daccalibration.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_daccalibration.o moc_daccalibration.cpp

moc_mydataport.o: moc_mydataport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mydataport.o moc_mydataport.cpp

moc_calibrationcheck.o: moc_calibrationcheck.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calibrationcheck.o moc_calibrationcheck.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

